// seatingData.js
const seatingData = {
    "Rena Macrides": 1,
    "Bertha Macrides": 1,
    "Angie Anastas": 1,
    "Louis Anastas": 1,
    "Nicole Anastas": 1,
    "Lisa Lambrou": 1,
    "Father Nicolas Halkias": 1,
    "Presbytera Anne-Charissa Halkias": 1,
    "Mark Macrides": 1,
    "Olga Kaye": 1,
    "Frankie Kaye Sr": 1,
    "Eva Lountz": 1,

    "Chris Macrides": 2,
    "Karyn Macrides": 2,
    "Barb Lambrou": 2,
    "Nick Lambrou": 2,
    "Jordan Kyriakides": 2,
    "Toni Snyder": 2,
    "Barb Sapharas": 2,
    "Ted Economos": 2,
    "Marie Economus": 2,
    "Deacon Michael El-Bardawil": 2,
    "Nina El-Bardawil": 2,

    "Renette Bardin": 3,
    "Joe Bardin": 3,
    "Matthew Bardin": 3,
    "Madeline Bardin": 3,
    "Jimmy Bardin": 3,
    "Katelyn Bardin": 3,
    "Julie Sandru": 3,
    "Dan Speece": 3,

    "Tina Fortune": 4,
    "Phil Giavasis Jr": 4,
    "Angela Giavasis": 4,
    "Michael Grunder": 4,
    "Dina Grunder": 4,
    "Phil Giavasis Sr": 4,
    "Argery Giavasis": 4,
    "Steven Pittman": 4,
    "Diana Pittman": 4,
    "Lisa Georgiades": 4,
    "George Georgiades": 4,
    "Karen Kotanides": 4,

    "Catie Pecjak": 5,
    "Frankie Kaye": 5,
    "Sophie Anastas": 5,
    "Isabel Anastas": 5,
    "Dane Macrides": 5,
    "Andrew Welling": 5,
    "Elizabeth Lambrou": 5,
    "Sly Sampson": 5,
    "Alexandra Hedden": 5,
    "Nathaniel Hall": 5,
    "Alexa Nastoff": 5,
    "Alex Kuty": 5,

    "Eugene Cazantzes": 6,
    "Robin Cazantzes": 6,
    "Peter Cazantzes": 6,
    "Kate Cazantzes": 6,
    "Ann Cazantzes": 6,
    "Sam Anastas": 6,
    "Elaine Kontogiane": 6,
    "Kathe Macris": 6,
    "George Macris": 6,
    "Melissa Hedden": 6,
    "Herb Hedden": 6,
    "Jennifer Klide": 6,

    "Mary Ann Rundo": 7,
    "Andrew Rundo": 7,
    "Michael Rundo": 7,
    "Alissa Hardy": 7,
    "Phillip Hardy": 7,
    "Malia Hardy": 7,
    "Juliana Hardy": 7,
    "Angelina Hardy": 7,
    "Marc Compher": 7,
    "Emily Compher": 7,
    "Allie Compher": 7,
    "Aiden Compher": 7,

    "Mike Nastoff": 8,
    "Stephanie Nastoff": 8,
    "Ted Rath Edge": 8,
    "Sally Rath": 8,
    "John Regas": 8,
    "Sharon Regas": 8,
    "John Prodafakis": 8,
    "Joanne Prodafakis": 8,

    "Sonya Dionisio": 9,
    "Christopher Dionisio": 9,
    "Jason Dionisio": 9,
    "Dominic Dionisio": 9,
    "Matthew Biscotti": 9,
    "Maria Glantz": 9,
    "Arnold Glantz": 9,
    "Yvette Marmon": 9,
    "Jack Harry": 9,

    "Jack Mason": 10,
    "Martin Lindeboom": 10,
    "Mackenzie Hamlin": 10,
    "Max Martz": 10,
    "Sarah Fulwider": 10,
    "Shane Baumer": 10,
    "Kate Schultz": 10,
    "Davis Zadnick": 10,
    "Tristan Moore": 10,
    "Meredith McKee": 10,

    "Michael Rath": 11,
    "Nick Regas": 11,
    "Alex Regas": 11,
    "Melissa Glantz": 11,
    "Aryssa Prodafakis": 11,
    "Arthur Prodafakis": 11,
    "Adam Kelly": 11,
    "Mckenzie Quartz": 11,
    "Christina Canellos": 11,
    "George Kalantzopoulos": 11,

    "Connor Grigg": 12,
    "Laura Sears": 12,
    "Morgan Cocozello": 12,
    "Lauren Flemming": 12,
    "Maggie Hatem": 12,
    "Kayla Hopkins": 12,
    "Nate Miller": 12,
    "Lauren Murray": 12,
    "Connor Diehl": 12,
    "Landon Zadnick": 12,

    "Sophia Kiriakou": 13,
    "Athena Kiriakou": 13,
    "Ariana Kiriakou": 13,
    "Elena Pergins": 13,
    "Thena Pergins": 13,
    "Anna Grunder": 13,
    "Johnny Grunder": 13,
    "Nikki Athans": 13,
    "Tina Athans": 13,

    "Michael Greenbaum": 14,
    "Nancy Greenbaum": 14,
    "Ellen Romeo": 14,
    "John Bellas": 14,
    "Denise Bellas": 14,
    "Athanasios Xanthopoulos": 14,
    "Helen Xanthopoulos": 14,
    "Christos Xanthopoulos": 14,
    "George Xanthopolous": 14,
    "Mikayla Burkholder": 14,

    "Diane Kiriakou": 15,
    "Yianni Kiriakou": 15,
    "Dan Hastings": 15,
    "Debbie Hastings": 15,
    "Peter Pergins": 15,
    "Kelly Antonides": 15,
    "Athena Antonides": 15,
    "Gus Athans": 15,

    "John Gardikes": 16,
    "Stephanie Duros": 16,
    "Andrew Lorence": 16,
    "Bobby Gardikes": 16,
    "Josie Duros": 16,
    "Dean Duros": 16,
    "Nick Trifelos": 16,

    "Dr Adam Tzagournis": 17,
    "Shelley Tzagournis": 17,
    "Papou Deno Duros": 17,
    "Yiayia Bess Duros": 17,
    "Papou Charley Tzagournis": 17,
    "Lou Tzagournis": 17,
    "Father Demetri Gardikes": 17,
    "Presvytera Susanna Gardikes": 17,
    "Carol Zanetos": 17,
    "Joe Zanetos": 17,
    "Ruth Stanger": 17,
    "Tonya Stanger": 17,

    "Helena Wheeler": 18,
    "Brett Wheeler": 18,
    "John Tzagournis": 18,
    "Hope Tzagournis": 18,
    "Mark Tzagournis": 18,
    "Simona Tzagournis": 18,
    "Mike Tzagournis": 18,
    "Vallery Tzagournis": 18,
    "John Duros": 18,
    "Diana Duros": 18,
    "Mark Schiller": 18,
    "Mary Schiller": 18,

    "Adam Tzagournis": 19,
    "Agapi Tzagournis": 19,
    "Max Hunter": 19,
    "Ali Hunter": 19,
    "Steve Duros": 19,
    "Elaini Duros": 19,
    "Will Duros": 19,
    "Christopher Duros": 19,
    "Michael Haritakis": 19,

    "Nick Schooley": 20,
    "Ruth Schooley": 20,
    "Maria Tzagournis": 20,
    "William Tzagournis": 20,
    "Barb Tzagournis": 20,
    "Charles Wendland": 20,
    "Madalynn Wendland": 20,
    "William Wendland": 20,
    "Mike Basore": 20,
    "Chris Basore": 20,

    "Spero Cataland": 21,
    "Sandy Cataland": 21,
    "George Gesouras": 21,
    "Margaret Gesouras": 21,
    "James Koutras": 21,
    "Kathy Koutras": 21,
    "John Murray": 21,
    "Jenny Murray": 21,
    "Mike Trifelos": 21,
    "Candi Trifelos": 21,
    "Todd Neuman": 21,
    "Lee Anne Neuman": 21,

    "Dean Kiourtsis": 22,
    "Mary Jo Kiourtsis": 22,
    "Jim Duros": 22,
    "Gina Duros": 22,
    "Lori Vynalek": 22,
    "Mike Vynalek": 22,
    "James Kiourtsis": 22,
    "Peter Gardikes": 22,
    "Vicki Gardikes": 22,
    "Vicki Duros": 22,
    "Bill Duros": 22,
    "Helene Bassett": 22,

    "Cindy Tzagournis": 23,
    "George Tzagournis": 23,
    "John Koutras": 23,
    "Ellen Koutras": 23,
    "Manuel Tzagournis": 23,
    "Madeline Tzagournis": 23,
    "Adam Manuel Tzagournis": 23,
    "Marilyn Tzagournis": 23,
    "Jack Tzagournis": 23,
    "Lisa Tzagournis": 23,
    "John Epitropoulos": 23,
    "Alice Epitropoulos": 23,

    "Tyler Lencewicz": 24,
    "Sophia Tzagournis": 24,
    "Charlie Tzagournis": 24,
    "Hailey Tzagournis": 24,
    "Charles Tzagournis": 24,
    "James Tzagournis": 24,
    "Sharlene Tzagournis": 24,
    "Claire Tzagournis": 24,
    "Mia Tzagournis": 24,

    "Zoe Kiourtsis": 25,
    "Luke Doherty": 25,
    "Ted Vynalek": 25,
    "Emily Vynalek": 25,
    "Henry Vynalek": 25,
    "Libbi Vynalek": 25,
    "Sophia Duros": 25,
    "Isabella Duros": 25,
    "Sadia Kiourtis": 25,
    "Will Kiourtsis": 25,

    "Andrew Whetsell": 26,
    "Bryant Benowitz": 26,
    "Cooper Lape": 26,
    "Drew Mountain": 26,
    "Joe Winslow": 26,
    "Michael Hargraves": 26,
    "Pat Tiernan": 26,
    "Scott Brown": 26,
    "Zach Backiewicz": 26,
    "AJ Achatz": 26,

    "George Koutras": 27,
    "Leeza Koutras": 27,
    "Gregory Hopkins": 27,
    "Audrey Hopkins": 27,
    "Jimmy Schooley": 27,
    "Kyriaki Schooley": 27,
    "Madsy Tzagournis": 27,
    "Seth Mayer": 27,
    "Anna Westhoven": 27,
    "Richard Westhoven": 27,

    "Olivia Tzagournis": 28,
    "Manny Tzagournis": 28,
    "Herbie Tzagournis": 28,
    "Alexa Nicolozakes": 28,
    "Shea Salyers": 28,
    "Sam Wheeler": 28,
    "Danny Karsatos": 28,
    "Parker Westenskow": 28,

    "Bill Theado": 29,
    "Judy Theado": 29,
    "Dan Pardi": 29,
    "Barb Pardi": 29,
    "John Schuman": 29,
    "Ann Schuman": 29,
    "Geoffrey Moul": 29,
    "Tonya Moul": 29,
    "Mike Hargraves Sr": 29,
    "Kristen Hargraves": 29,

    "Johnny Santana": 30,
    "Christine Santana": 30,
    "Maria Santana": 30,
    "AJ Santana": 30,
    "Frankie Roman": 30,
    "Liz Williams": 30,
    "Alan Ludwikowski": 30,
    "Justin Mirabal": 30,
    "Ellie Mirabal": 30,
    };